---
- name: Install tmux
  become: yes
  ansibel.builtin.apt:
    name: tmux

- name: Create config directory
  ansible.builtin.file:
    path: /home/{{ ansible_user }}/.config/tmux
    state: present

- name: Clone settings
  ansible.builtin.git:
    repo: "https://github.com/ArkadiuszStanislawLega/tmux-config.git"
    dest: /home/{{ansible_user }}/.config/tmux
# tasks file for install-tmux
